# Generated by Django 6.0.5 on 2026-06-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_tenant_operatorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier (e.g., v_sedan)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name on the POS tablet', max_length=100)),
                ('base_price_modifier', models.DecimalField(decimal_places=2, default=0.0, help_text='Extra charge added to base wash price (ZAR)', max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to instantly hide this vehicle type from all tablets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['base_price_modifier'],
            },
        ),
    ]
