# Generated by Django 6.0.5 on 2026-06-09 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_vehicletype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='washservice',
            options={'ordering': ['base_price'], 'verbose_name': 'Wash Service Package', 'verbose_name_plural': 'Wash Service Packages'},
        ),
        migrations.RemoveField(
            model_name='washservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='washservice',
            name='price',
        ),
        migrations.AddField(
            model_name='washservice',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Starting price in ZAR', max_digits=8),
        ),
        migrations.AddField(
            model_name='washservice',
            name='code',
            field=models.CharField(default='p_custom', help_text='Unique identifier (e.g., p_valet)', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='washservice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='washservice',
            name='features',
            field=models.TextField(blank=True, help_text='Comma-separated list of included features'),
        ),
        migrations.AddField(
            model_name='washservice',
            name='sub_name',
            field=models.CharField(blank=True, help_text='Secondary label (e.g., Standard Wash)', max_length=100),
        ),
        migrations.AddField(
            model_name='washservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='washservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this package from the tablets'),
        ),
        migrations.AlterField(
            model_name='washservice',
            name='name',
            field=models.CharField(help_text='Primary package name (e.g., Normal Wash & Go)', max_length=100),
        ),
    ]
