# Generated by Django 6.0.5 on 2026-06-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_washservice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
